"""Golden legacy protocol and non-destructive file conversion checks."""
import importlib.util
from pathlib import Path
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[1]
spec = importlib.util.spec_from_file_location("migration", ROOT / "tools/migrate-localisation.py")
migration = importlib.util.module_from_spec(spec)
spec.loader.exec_module(migration)


class MigrationTests(unittest.TestCase):
    def test_four_markers_and_formatting(self):
        # Fixed protocol vectors, not generated by a matching encoder.
        source = "§Y\x10-N\x11\x0eN\x12\xf9R\x13it§! £adm£ $COUNTRY$ \\n"
        decoded, counts = migration.decode_legacy(source)
        self.assertEqual(decoded, "§Y中一对\u7d5b§! £adm£ $COUNTRY$ \\n")
        self.assertEqual(counts["sequences"], 4)

    def test_cp1252_pua_and_surrogates(self):
        self.assertEqual(migration.decode_legacy("\x10\x00€")[0], "耀")
        self.assertEqual(migration.decode_legacy("\x10\x01á")[0], "ā")
        self.assertEqual(migration.decode_legacy("\x10=Ø\x10\x00Þ")[0], "😀")
        self.assertEqual(migration.decode_legacy("\x10\x81N")[0], "亁")
        self.assertEqual(migration.decode_legacy("already 中文 𠀀")[0], "already 中文 𠀀")

    def test_invalid_sequences(self):
        for text in ["\x10", "\x11a", "\x10中N", "\x10=Ø"]:
            with self.assertRaises((ValueError, UnicodeError)):
                migration.decode_legacy(text)

    def test_copy_preserves_source_bom_and_syntax(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source, destination = root / "source", root / "copy"
            source.mkdir()
            raw = '\ufeffl_english:\r\n KEY:0 "§Y\x10-N§! $TAG$" # comment\r\n'.encode("utf-8")
            (source / "test.yml").write_bytes(raw)
            report = migration.convert_directory(source, destination)
            self.assertEqual((source / "test.yml").read_bytes(), raw)
            self.assertEqual((destination / "test.yml").read_bytes(), '\ufeffl_english:\r\n KEY:0 "§Y中§! $TAG$" # comment\r\n'.encode("utf-8"))
            self.assertEqual(report["sequences"], 1)
            self.assertTrue((destination / "unicode-migration.json").exists())
            with self.assertRaises(ValueError):
                migration.convert_directory(source, destination)

    def test_error_precedes_destination_creation(self):
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            source, destination = root / "source", root / "copy"
            source.mkdir()
            (source / "valid.yml").write_text("valid", encoding="utf-8")
            (source / "invalid.yml").write_text("\x10", encoding="utf-8")
            with self.assertRaises(ValueError):
                migration.convert_directory(source, destination)
            self.assertFalse(destination.exists())


if __name__ == "__main__":
    unittest.main()
